#!/usr/bin/env sh
# . "${0%/*}/h"

npx --no -- commitlint --edit $1

current_version=$(jq -r '.version' package.json)
last_version=$(cat .package.version)

# Chamar a função de teste usando Node.js
result=$(node -e "const versionTester = require('./semverCompare.cjs'); console.log(versionTester.test('$current_version', '$last_version'));")

# Verificar o resultado da função de teste
if [ "$result" = "true" ]; then
    echo "Version: "$current_version""
    echo "$current_version" > .package.version
    git tag -a "$current_version" -m "Versão $current_version"
    git add .package.version
    exit 0
else
    echo "A versão atual é menor ou igual à versão anterior."
    echo "current: "$current_version" | last: "$last_version"" 
    echo ""
    echo "run 'yarn version-select'"
    exit 1
fi



