#!/usr/bin/env sh
# . "${0%/*}/h"

# Extrair a versão atual do package.json
current_version=$(jq -r '.version' package.json)
last_version=$(cat .package.version)

current_version_number=$(echo "$current_version" | tr -dc '0-9\n' | bc)
last_version_number=$(echo "$last_version" | tr -dc '0-9\n' | bc)
echo "### PACKAGE VERSION ###"
echo "CURRENT: "$current_version_number""
echo "LAST: "$last_version_number""
echo ""

if [ "$current_version_number" -le "$last_version_number"  ]; then
    echo "The version is minor or equal."
    echo "Run the command 'yarn version-select'."
    # yarn version-select 
    exit 1
fi

# Salvar a versão atual no arquivo
git add .package.version
echo "$current_version" > .package.version