name: Releases
on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: "true"
          release-count: "0"
          skip-tag: "true"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          #tag_name: ${{ steps.changelog.outputs.tag }}
          #release_name: Release ${{ github.ref }}
          release_name: ${{ steps.changelog.outputs.tag }}
          #body: |
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
